apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin-helm.fullname" . }}
  labels:
    {{- include "jellyfin-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webport }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.dlnaport }}
      targetPort: dlna
      protocol: UDP
      name: dlna
  selector:
    {{- include "jellyfin-helm.selectorLabels" . | nindent 4 }}
